# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Create app directory
WORKDIR /app

# Copy project metadata
COPY pyproject.toml uv.lock README.md ./
# Copy source code
COPY current_water_levels.py ./

# Install dependencies
RUN pip install --no-cache-dir .

# Set default workdir
WORKDIR /app

# Default command
CMD ["python", "current_water_levels.py"]
